# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [143]:
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [ ]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [ ]:
vec.shape

(40,)

5. Print the type of the previous array in question 3

In [ ]:
vec.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [ ]:
print("Version: ")
print(np.__version__)
print("\n\nConfig: ")
print(np.show_config())

Version: 
1.18.5


Config: 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [ ]:
vec.ndim

1

8. Create a boolean array with all the True values

In [146]:
bool_arr = np.ones((8,5),dtype=bool)
bool_arr

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

9. Create a two dimensional array




In [147]:
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

10. Create a three dimensional array



In [ ]:
threeD = np.array([[[1,2,3],[2,3,4]]])
threeD

array([[[1, 2, 3],
        [2, 3, 4]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
a = a.ravel()
reversed = a[::-1]
reversed

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1])

In [ ]:
threeD[::-1,::-1,::-1]

array([[[4, 3, 2],
        [3, 2, 1]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [149]:
null = np.empty(10,dtype=int)
null[5] = 1
null

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [ ]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [153]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [155]:
arr1 = np.array([[1., 2., 3.]])
arr2 = np.array([[0., 4., 1.]])
arr1 * arr2

array([[0., 8., 3.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [36]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [11]:
arr = np.arange(10)
arr[1::2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [13]:
arr[1::2] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [162]:
arr = np.arange(10)
ind = [5,6,7]
arr[ind] = [8,9,10]
arr

array([ 0,  1,  2,  3,  4,  8,  9, 10,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [35]:
arr2d = np.ones((4,8))
arr2d[1:3,1:7] = 0
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [173]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[(arr2d>4)] = -1
arr2d

array([[ 1,  2,  3],
       [ 4, -1, -1],
       [-1, -1, -1]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [51]:
arr2d = np.arange(10).reshape(2,5)
sliced = arr2d[0]
sliced

array([0, 1, 2, 3, 4])

In [54]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [55]:
arr2d = np.arange(10).reshape(2,5)
sliced = arr2d[1,1]
sliced

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [57]:
arr2d = np.arange(10).reshape(2,5)
sliced = arr2d[0:2,2]
sliced

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [65]:
arr = np.array([np.random.randint(0,100) for i in range(100) ]).reshape(10,10)
arr

array([[ 4, 93, 51, 62,  0, 53, 83, 31, 19, 43],
       [90, 77, 35, 35, 55,  3, 74,  0, 65, 13],
       [99, 26, 87, 52, 48, 31,  4, 83, 36, 14],
       [ 3, 48, 31, 28, 64, 48, 74, 76, 19, 98],
       [22, 67, 55, 60, 17, 33, 50, 89, 22, 64],
       [46, 82, 45, 50, 59,  8, 49, 64, 51,  5],
       [ 2, 59,  5, 58, 36, 78,  9, 35,  4, 13],
       [19, 32, 22, 65, 63, 31, 50, 66, 56, 29],
       [31, 51, 90,  7, 61, 14, 85, 92, 32, 57],
       [34, 91, 13, 20, 37, 39, 44, 48, 27, 30]])

###Or

In [179]:
##can be done with this method as well
arr = np.random.randint(100,size=(100)).reshape(10,10)
arr

array([[71, 95, 92, 34, 70, 70, 14, 71, 22, 98],
       [63, 28, 30, 55, 20, 40, 93, 16, 55, 62],
       [30, 98, 53, 48, 57, 17, 38,  2, 11, 51],
       [84, 19, 79, 50, 13, 13, 23, 51, 29, 10],
       [68, 92, 44, 20,  4, 23, 30, 49, 67, 95],
       [57, 78, 69, 80, 99, 75, 53,  8, 80,  0],
       [56, 77, 30, 98, 74, 60, 45,  5, 42, 28],
       [ 0, 23, 79, 13, 82, 28,  1, 63, 31, 56],
       [62, 27,  0, 91, 43, 35, 33, 72, 34, 45],
       [20, 45, 14, 58, 21, 97, 50, 34, 97,  7]])

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [72]:
a = np.array([1,2,3,2,3,4,3,4,5,6]);b = np.array([7,2,10,2,7,4,9,4,9,8])
common = (a[a == b])
common

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6]); b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a == b]

array([2, 2, 4, 4])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [79]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Will"]

array([[-0.66835256, -1.34187226, -1.39863481, -1.58555165],
       [ 1.66029925, -1.16497197, -1.08715886, -0.86777765],
       [-2.15488716, -0.71997158, -0.43488073, -0.26834329],
       [ 0.22736191,  1.51537511, -2.18682682, -0.54640628],
       [ 0.89458117,  0.26131847,  0.07540413, -0.51172928]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [81]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != ("Will" and "Joe")]

array([[ 0.88888009,  0.04527976, -0.05218788, -0.54131873],
       [-1.75515305, -0.18864405, -1.4882751 ,  0.26761275],
       [ 1.00300364,  1.66819061, -1.78421981,  1.12101834],
       [-0.53066887, -0.60360798,  0.65668134, -0.92293398]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [84]:
arr2d = np.arange(1,16.).reshape(5,3)
arr2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [86]:
arr2d = np.arange(1,17.).reshape(2,2,4)
arr2d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [90]:
arr2d.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [92]:
arr = np.sqrt(np.arange(10))
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [106]:
arr1 = np.random.randint(100,size=12)
arr2 = np.random.randint(100,size=12)
arr3 = np.empty(12)
mask = (arr1 > arr2) | (arr2 > arr1)
arr3[mask]

array([1.83e-322, 3.46e-323, 5.43e-323, 8.89e-323, 4.30e-322])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [113]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted = np.sort(np.unique(names))
sorted

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [122]:
a = np.array([1,2,3,4,5]) ;b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [133]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
np.delete(sampleArray,[0])
newArray = np.vstack([newColumn,sampleArray])
newArray

array([[10, 10, 10],
       [34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [135]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]); y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot = np.dot(x,y)
dot

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [141]:
arr = np.random.randint(100,size=20)
cumsum = np.cumsum(arr)
cumsum

array([ 10,  22, 111, 184, 232, 320, 372, 388, 398, 435, 458, 542, 560,
       582, 613, 663, 733, 795, 834, 838])