In [1]:
import numpy as np

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
a = np.arange(10)
splited = np.split(a,2)
arr2d = np.array(splited).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype=np.int32).reshape(2,5)
np.vstack([arr1,arr2])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [13]:
np.hstack([arr1,arr2])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrOfarr = np.array([list(np.random.randn(2,3) for i in range(2))])
flattened = arrOfarr.ravel()
flattened

array([-0.46524568,  1.61193795, -0.71783513, -0.44463008,  0.38715078,
       -1.88533278, -0.86520643,  0.80013344, -1.94543275,  2.30279636,
       -0.74298683, -0.0244165 ])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [22]:
a = np.random.rand(10*4*4).reshape(4,4,10)
oneD = a.ravel()
oneD

array([0.12685059, 0.27178615, 0.86347731, 0.75800896, 0.63368186,
       0.40608998, 0.06887567, 0.45778045, 0.45853892, 0.25039803,
       0.28946818, 0.16083501, 0.72310848, 0.14561762, 0.62400834,
       0.5654387 , 0.05147003, 0.83299077, 0.61310546, 0.61632705,
       0.82517575, 0.82536006, 0.54229537, 0.92439498, 0.50823501,
       0.2994161 , 0.09858711, 0.35786196, 0.04505667, 0.17061461,
       0.70740194, 0.29946156, 0.64801691, 0.52116146, 0.68873644,
       0.06118926, 0.36466527, 0.4766879 , 0.92292923, 0.98463272,
       0.39463712, 0.62146141, 0.76354993, 0.69443843, 0.81076458,
       0.59686601, 0.04604352, 0.33945607, 0.29129868, 0.13660666,
       0.48746785, 0.58396181, 0.87885682, 0.12894491, 0.38301576,
       0.1391479 , 0.54422277, 0.74882082, 0.46469469, 0.01731008,
       0.09254229, 0.52667861, 0.8652112 , 0.39361353, 0.92071609,
       0.30751925, 0.42447972, 0.14201396, 0.37080838, 0.6943078 ,
       0.56122965, 0.16341511, 0.02777448, 0.10246891, 0.24662

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [30]:
a = np.arange(15)
np.array(np.split(a,5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
arr = np.random.randn(5,5)
np.square(arr)

array([[9.02529736e-02, 6.52141562e-02, 4.68373478e-01, 1.76532659e+00,
        2.60245517e+00],
       [3.71264002e-01, 1.66266866e-02, 2.47252801e-02, 1.15710717e+00,
        9.04101397e-02],
       [2.45530073e+00, 8.13589228e-01, 8.72806198e-01, 9.17213030e-01,
        1.67029950e+00],
       [3.64483992e-01, 1.87496603e+00, 1.87658082e+00, 1.61023772e+00,
        3.67453693e-01],
       [4.75772479e+00, 4.83742635e-03, 2.57605989e+00, 9.30243260e-03,
        3.23008379e-03]])

## Question:8

### Create 5x6 an array and find the mean?

In [34]:
a = np.random.randn(5,6)
a.mean()

0.014817603495794565

## Question:9

### Find the standard deviation of the previous array in Q8?

In [35]:
a.std()

1.0686066956591238

## Question:10

### Find the median of the previous array in Q8?

In [37]:
np.median(a)

0.11295456292513631

## Question:11

### Find the transpose of the previous array in Q8?

In [38]:
a.T

array([[ 2.54315904,  0.12024263, -0.96577048, -0.29496015,  0.08044074],
       [ 1.00173874,  0.91419771, -0.33099285,  0.78965063,  0.15125706],
       [ 0.81220907,  0.10566649,  1.60759388,  1.21896658,  0.2093729 ],
       [-1.15788157,  0.71417145, -0.78151864, -0.32720341,  0.2721217 ],
       [ 0.66291845, -2.69630918, -1.31368094,  0.07885106, -0.9552699 ],
       [ 0.81630253, -0.04365121,  0.35937782, -2.13516323, -1.01130883]])

In [39]:
np.transpose(a)

array([[ 2.54315904,  0.12024263, -0.96577048, -0.29496015,  0.08044074],
       [ 1.00173874,  0.91419771, -0.33099285,  0.78965063,  0.15125706],
       [ 0.81220907,  0.10566649,  1.60759388,  1.21896658,  0.2093729 ],
       [-1.15788157,  0.71417145, -0.78151864, -0.32720341,  0.2721217 ],
       [ 0.66291845, -2.69630918, -1.31368094,  0.07885106, -0.9552699 ],
       [ 0.81630253, -0.04365121,  0.35937782, -2.13516323, -1.01130883]])

In [40]:
a.T.shape

(6, 5)

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
arr = np.random.randn(4,4)*10
print(arr)
print("Sum of Diagonals: ",np.sum(np.diag(arr)))


[[-14.03682274  -1.55293437   4.30255488  -4.90618937]
 [ 10.46588873  -4.00344296  -5.8372132   -4.89428912]
 [-10.4443099    9.10327056   7.22922443  -5.95125556]
 [  2.39538406  -4.27594146   5.72318911  -2.41035246]]
Sum of Diagonals:  -13.221393724543976


## Question:13

### Find the determinant of the previous array in Q12?

In [48]:
np.linalg.det(arr)

11892.09600878383

## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
np.percentile(arr,[5,95])

array([-11.34243811,   9.4439251 ])

## Question:15

### How to find if a given array has any null values?

In [51]:
np.isnan(arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])